import type { School } from "./types";

export const schools: School[] = [
    {
    id: "agustus-tolton",
    name: "Augustus Tolton",
    latitude: 41.76,
    longitude: -87.62,
  },
  {
    id: "bethesda-academy",
    name: "Bethesda International Academy",
    latitude: 42.01,
    longitude: -87.69,
  },
  {
    id: "cambridge",
    name: "Cambridge School",
    latitude: 41.81,
    longitude: -87.60,
  },
  {
    id: "chicago-sda",
    name: "Chicago SDA Academy",
    latitude: 41.77,
    longitude: -87.62,
  },
  {
    id: "chicago-west-side",
    name: "Chicago West Side Christian School",
    latitude: 41.87,
    longitude: -87.73,
  },
  {
    id: "children-of-peace",
    name: "Children of Peace Catholic School",
    latitude: 41.87,
    longitude: -87.67,
  },
  {
    id: "daystar",
    name: "Daystar Academy",
    latitude: 41.86,
    longitude: -87.63,
  },
  {
    id: "depaul-college-prep",
    name: "DePaul College Prep",
    latitude: 41.94,
    longitude: -87.69,
  },
  {
    id: "good-shepherd",
    name: "Good Shepherd Catholic School",
    latitude: 41.84,
    longitude: -87.73,
  },
  {
    id: "heritage-leadership",
    name: "Heritage Leadership Academy",
    latitude: 41.69,
    longitude: -87.66,
  },
  {
    id: "holy-angels",
    name: "Holy Angels Catholic School",
    latitude: 41.82,
    longitude: -87.61,
  },
  {
    id: "hope-excel",
    name: "HOPE Excel Academy",
    latitude: 41.89,
    longitude: -87.75,
  },
  {
    id: "icci-academy",
    name: "ICCI Academy",
    latitude: 41.94,
    longitude: -87.79,
  },
  {
    id: "ita-vla",
    name: "ITA Village Leadership Academy",
    latitude: 41.80,
    longitude: -87.60,
  },
  {
    id: "lydia-home",
    name: "LYDIA Home",
    latitude: 41.95,
    longitude: -87.74,
  },
  {
    id: "makki-academy",
    name: "Makki Educational Academy",
    latitude: 41.97,
    longitude: -87.71,
  },
  {
    id: "mercy-boys",
    name: "Mercy School for Boys",
    latitude: 41.87,
    longitude: -87.65,
  },
  {
    id: "mercy-girls",
    name: "Mercy School for Girls",
    latitude: 41.87,
    longitude: -87.65,
  },
  {
    id: "oakdale",
    name: "Oakdale Christian Academy",
    latitude: 41.72,
    longitude: -87.65,
  },
  {
    id: "ravenswood-baptist",
    name: "Ravenswood Baptist Christian",
    latitude: 41.96,
    longitude: -87.67,
  },
  {
    id: "st-ailbe",
    name: "St. Ailbe School",
    latitude: 41.73,
    longitude: -87.59,
  },
  {
    id: "st-catherine",
    name: "St. Catherine - St. Lucy Catholic School",
    latitude: 41.88,
    longitude: -87.78,
  },
  {
    id: "st-johns",
    name: "St. John's Lutheran School",
    latitude: 41.96,
    longitude: -87.74,
  },
  {
    id: "st-margaret",
    name: "St. Margaret of Scotland School",
    latitude: 41.70,
    longitude: -87.66,
  },
  {
    id: "st-paul-lutheran",
    name: "St. Paul Lutheran School",
    latitude: 41.75,
    longitude: -87.59,
  },
  {
    id: "st-philip-neri",
    name: "Saint Philip Neri School",
    latitude: 41.76,
    longitude: -87.57,
  },
  {
    id: "st-sabina",
    name: "St. Sabina Academy",
    latitude: 41.75,
    longitude: -87.66,
  },
  {
    id: "st-viator",
    name: "St. Viator Elementary School",
    latitude: 41.95,
    longitude: -87.73,
  },
  {
    id: "visitation-catholic",
    name: "Visitation Catholic School",
    latitude: 41.80,
    longitude: -87.64,
  },
];
